apiVersion: apps/v1
kind: Deployment
metadata:
  name: camunda
  labels:
    app: camunda
spec:
  replicas: 1
  selector:
    matchLabels:
      app: camunda
  template:
    metadata:
      labels:
        app: camunda
    spec:
      containers:
        - name: camunda
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: AZURE_CLIENT_ID
              value: "{{ .Values.azureKeyVault.clientId }}"
            - name: AZURE_CLIENT_SECRET
              value: "{{ .Values.azureKeyVault.clientSecret }}"
            - name: AZURE_TENANT_ID
              value: "{{ .Values.azureKeyVault.tenantId }}"
            - name: KEY_VAULT_NAME
              value: "{{ .Values.azureKeyVault.keyVaultName }}"
          command: ["/bin/bash", "-c", "/camunda/scripts/retrieve_secrets.sh && /camunda/bin/catalina.sh run"]
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /camunda
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /camunda
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
