{{- if and .Values.ingress.tlsEnabled .Values.tls.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.ingress.tlsSecretName }}
  labels:
    app: camunda
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.tls.cert }}
  tls.key: {{ .Values.tls.key }}
{{- end }}
